[versions]
agp = "8.2.0"
compileSdk = "37"
targetSdk = "37"
minSdk = "35"
appcompat = "1.7.0"
preference = "1.2.1"
[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
