[versions]
agp = "8.4.0"
compileSdk = "36"
targetSdk = "36"
minSdk = "35"
kotlin = "1.9.24"
appcompat = "1.7.0"
layoutlib = "2024.1.1"
preference = "1.2.1"
core = "1.13.1"
[libraries]
android-layoutlib = { group = "com.android.tools.layoutlib", name = "layoutlib-api", version.ref = "layoutlib" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
