plugins {
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.android.angle'
    compileSdk = 36

    defaultConfig {
        applicationId "com.android.angle"
        minSdk = 35
        targetSdk = 36
        versionCode 100
        versionName "100"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'org.jetbrains.kotlin') {
            if (requested.name == 'kotlin-stdlib-jdk7' || requested.name == 'kotlin-stdlib-jdk8') {
                details.useTarget("org.jetbrains.kotlin:kotlin-stdlib:1.9.24")
            }
        }
    }
}
dependencies {
    implementation libs.androidx.core
    implementation libs.androidx.appcompat
    implementation libs.androidx.preference
}
